export const expected = {
  "boxShadow": {
    "shadow-sm": "0px 1px 2px 0px #0000000d",
  },
  "colors": {
    "brand-50": "#fdeee9",
    "brand-100": "#faccbe",
    "brand-200": "#f7ab93",
    "brand-300": "#f38968",
    "brand-400": "#f0673d",
    "brand-500": "#ed4612",
    "brand-600": "#c2390f",
    "brand-700": "#972c0c",
    "brand-800": "#6c2008",
    "brand-900": "#411305",
    "brand-950": "#150602",
    "grey-50": "#f9fafb",
    "grey-100": "#f1f5f9",
    "grey-200": "#e5e7eb",
    "grey-300": "#d1d5db",
    "grey-400": "#9ca3af",
    "grey-500": "#6b7280",
    "grey-600": "#475569",
    "grey-700": "#334155",
    "grey-800": "#1e293b",
    "grey-900": "#111827",
    "grey-950": "#020617",
    "green-50": "#f0fdf4",
    "green-100": "#dcfce7",
    "green-200": "#bbf7d0",
    "green-300": "#86efac",
    "green-400": "#4ade80",
    "green-500": "#22c55e",
    "green-600": "#16a34a",
    "green-700": "#15803d",
    "green-800": "#166534",
    "green-900": "#14532d",
    "green-950": "#052e16",
    "red-50": "#fef2f2",
    "red-100": "#fee2e2",
    "red-200": "#fecaca",
    "red-300": "#fca5a5",
    "red-400": "#f87171",
    "red-500": "#ef4444",
    "red-600": "#dc2626",
    "red-700": "#b91c1c",
    "red-800": "#991b1b",
    "red-900": "#7f1d1d",
    "red-950": "#450a0a",
    "rose-50": "#fff1f2",
    "rose-100": "#ffe4e6",
    "rose-200": "#fecdd3",
    "rose-300": "#fda4af",
    "rose-400": "#fb7185",
    "rose-500": "#f43f5e",
    "rose-600": "#e11d48",
    "rose-700": "#be123c",
    "rose-800": "#9f1239",
    "rose-900": "#881337",
    "rose-950": "#4c0519",
    "white-text-white": "#ffffff",
  },
  "fontFamilies": {
    "primary": {
      "var": "var(--font-primaryFont)",
      "value": "Inter",
    },
  },
  "fontSize": {
    "0": "12px",
    "1": "14px",
    "2": "16px",
    "3": "18px",
    "4": "20px",
    "5": "24px",
    "6": "30px",
    "7": "36px",
    "8": "48px",
    "9": "60px",
    "10": "72px",
    "11": "96px",
    "12": "128px",
  },
  "lineHeight": {
    "0": "16px",
    "1": "20px",
    "2": "24px",
    "3": "28px",
    "4": "32px",
    "5": "36px",
    "6": "40px",
    "7": "48px",
    "8": "60px",
    "9": "72px",
    "10": "96px",
    "11": "128px",
  },
  "typography": {},
  "borderRadius": {},
}

export const inputData = {
  "Tailwind Template": {
    "text": {
      "brand": {
        "50": {
          "value": "#fdeee9",
          "type": "color",
        },
        "100": {
          "value": "#faccbe",
          "type": "color",
        },
        "200": {
          "value": "#f7ab93",
          "type": "color",
        },
        "300": {
          "value": "#f38968",
          "type": "color",
        },
        "400": {
          "value": "#f0673d",
          "type": "color",
        },
        "500": {
          "value": "#ed4612",
          "type": "color",
        },
        "600": {
          "value": "#c2390f",
          "type": "color",
        },
        "700": {
          "value": "#972c0c",
          "type": "color",
        },
        "800": {
          "value": "#6c2008",
          "type": "color",
        },
        "900": {
          "value": "#411305",
          "type": "color",
        },
        "950": {
          "value": "#150602",
          "type": "color",
        },
      },
      "grey": {
        "50": {
          "value": "#f8fafc",
          "type": "color",
        },
        "100": {
          "value": "#f1f5f9",
          "type": "color",
        },
        "200": {
          "value": "#e2e8f0",
          "type": "color",
        },
        "300": {
          "value": "#d1d5db",
          "type": "color",
        },
        "400": {
          "value": "#9ca3af",
          "type": "color",
        },
        "500": {
          "value": "#6b7280",
          "type": "color",
        },
        "600": {
          "value": "#475569",
          "type": "color",
        },
        "700": {
          "value": "#334155",
          "type": "color",
        },
        "800": {
          "value": "#1e293b",
          "type": "color",
        },
        "900": {
          "value": "#111827",
          "type": "color",
        },
        "950": {
          "value": "#020617",
          "type": "color",
        },
      },
      "green": {
        "50": {
          "value": "#f0fdf4",
          "type": "color",
        },
        "100": {
          "value": "#dcfce7",
          "type": "color",
        },
        "200": {
          "value": "#bbf7d0",
          "type": "color",
        },
        "300": {
          "value": "#86efac",
          "type": "color",
        },
        "400": {
          "value": "#4ade80",
          "type": "color",
        },
        "500": {
          "value": "#22c55e",
          "type": "color",
        },
        "600": {
          "value": "#16a34a",
          "type": "color",
        },
        "700": {
          "value": "#15803d",
          "type": "color",
        },
        "800": {
          "value": "#166534",
          "type": "color",
        },
        "900": {
          "value": "#14532d",
          "type": "color",
        },
        "950": {
          "value": "#052e16",
          "type": "color",
        },
      },
      "red": {
        "50": {
          "value": "#fef2f2",
          "type": "color",
        },
        "100": {
          "value": "#fee2e2",
          "type": "color",
        },
        "200": {
          "value": "#fecaca",
          "type": "color",
        },
        "300": {
          "value": "#fca5a5",
          "type": "color",
        },
        "400": {
          "value": "#f87171",
          "type": "color",
        },
        "500": {
          "value": "#ef4444",
          "type": "color",
        },
        "600": {
          "value": "#dc2626",
          "type": "color",
        },
        "700": {
          "value": "#b91c1c",
          "type": "color",
        },
        "800": {
          "value": "#991b1b",
          "type": "color",
        },
        "900": {
          "value": "#7f1d1d",
          "type": "color",
        },
        "950": {
          "value": "#450a0a",
          "type": "color",
        },
      },
      "rose": {
        "50": {
          "value": "#fff1f2",
          "type": "color",
        },
        "100": {
          "value": "#ffe4e6",
          "type": "color",
        },
        "200": {
          "value": "#fecdd3",
          "type": "color",
        },
        "300": {
          "value": "#fda4af",
          "type": "color",
        },
        "400": {
          "value": "#fb7185",
          "type": "color",
        },
        "500": {
          "value": "#f43f5e",
          "type": "color",
        },
        "600": {
          "value": "#e11d48",
          "type": "color",
        },
        "700": {
          "value": "#be123c",
          "type": "color",
        },
        "800": {
          "value": "#9f1239",
          "type": "color",
        },
        "900": {
          "value": "#881337",
          "type": "color",
        },
        "950": {
          "value": "#4c0519",
          "type": "color",
        },
      },
      "white": {
        "text-white": {
          "value": "#ffffff",
          "type": "color",
        },
      },
    },
    "ring": {
      "grey": {
        "200": {
          "value": "#e5e7eb",
          "type": "color",
        },
        "300": {
          "value": "#d1d5db",
          "type": "color",
        },
      },
      "red": {
        "500": {
          "value": "#ef4444",
          "type": "color",
        },
      },
    },
    "bg": {
      "grey": {
        "50": {
          "value": "#f9fafb",
          "type": "color",
        },
      },
      "red": {
        "50": {
          "value": "#fef2f2",
          "type": "color",
        },
      },
      "green": {
        "50": {
          "value": "#f0fdf4",
          "type": "color",
        },
      },
    },
    "Shadow": {
      "shadow-sm": {
        "value": {
          "color": "#0000000d",
          "type": "dropShadow",
          "x": 0,
          "y": 1,
          "blur": 2,
          "spread": 0,
        },
        "type": "boxShadow",
      },
    },
    "fontFamilies": {
      "primary": {
        "value": "Inter",
        "type": "fontFamilies",
      },
    },
    "lineHeights": {
      "0": {
        "value": "16",
        "type": "lineHeights",
      },
      "1": {
        "value": "20",
        "type": "lineHeights",
      },
      "2": {
        "value": "24",
        "type": "lineHeights",
      },
      "3": {
        "value": "28",
        "type": "lineHeights",
      },
      "4": {
        "value": "32",
        "type": "lineHeights",
      },
      "5": {
        "value": "36",
        "type": "lineHeights",
      },
      "6": {
        "value": "40",
        "type": "lineHeights",
      },
      "7": {
        "value": "48",
        "type": "lineHeights",
      },
      "8": {
        "value": "60",
        "type": "lineHeights",
      },
      "9": {
        "value": "72",
        "type": "lineHeights",
      },
      "10": {
        "value": "96",
        "type": "lineHeights",
      },
      "11": {
        "value": "128",
        "type": "lineHeights",
      },
    },
    "fontWeights": {
      "inter-0": {
        "value": "Extra Light",
        "type": "fontWeights",
      },
      "inter-1": {
        "value": "Regular",
        "type": "fontWeights",
      },
      "inter-2": {
        "value": "Medium",
        "type": "fontWeights",
      },
      "inter-3": {
        "value": "Semi Bold",
        "type": "fontWeights",
      },
      "inter-4": {
        "value": "Bold",
        "type": "fontWeights",
      },
    },
    "fontSize": {
      "0": {
        "value": "12",
        "type": "fontSizes",
      },
      "1": {
        "value": "14",
        "type": "fontSizes",
      },
      "2": {
        "value": "16",
        "type": "fontSizes",
      },
      "3": {
        "value": "18",
        "type": "fontSizes",
      },
      "4": {
        "value": "20",
        "type": "fontSizes",
      },
      "5": {
        "value": "24",
        "type": "fontSizes",
      },
      "6": {
        "value": "30",
        "type": "fontSizes",
      },
      "7": {
        "value": "36",
        "type": "fontSizes",
      },
      "8": {
        "value": "48",
        "type": "fontSizes",
      },
      "9": {
        "value": "60",
        "type": "fontSizes",
      },
      "10": {
        "value": "72",
        "type": "fontSizes",
      },
      "11": {
        "value": "96",
        "type": "fontSizes",
      },
      "12": {
        "value": "128",
        "type": "fontSizes",
      },
    },
    "letterSpacing": {
      "0": {
        "value": "0%",
        "type": "letterSpacing",
      },
    },
    "paragraphSpacing": {
      "0": {
        "value": "0",
        "type": "paragraphSpacing",
      },
    },
    "Primary": {
      "text-xs": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.0}",
            "fontSize": "{fontSize.0}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.0}",
            "fontSize": "{fontSize.0}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.0}",
            "fontSize": "{fontSize.0}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.0}",
            "fontSize": "{fontSize.0}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-sm": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.1}",
            "fontSize": "{fontSize.1}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.1}",
            "fontSize": "{fontSize.1}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.1}",
            "fontSize": "{fontSize.1}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.1}",
            "fontSize": "{fontSize.1}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-base": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.2}",
            "fontSize": "{fontSize.2}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.2}",
            "fontSize": "{fontSize.2}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.2}",
            "fontSize": "{fontSize.2}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.2}",
            "fontSize": "{fontSize.2}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-lg": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.3}",
            "fontSize": "{fontSize.3}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.3}",
            "fontSize": "{fontSize.3}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.3}",
            "fontSize": "{fontSize.3}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.3}",
            "fontSize": "{fontSize.3}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-xl": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.3}",
            "fontSize": "{fontSize.4}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.3}",
            "fontSize": "{fontSize.4}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.3}",
            "fontSize": "{fontSize.4}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.3}",
            "fontSize": "{fontSize.4}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-2xl": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.4}",
            "fontSize": "{fontSize.5}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.4}",
            "fontSize": "{fontSize.5}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.4}",
            "fontSize": "{fontSize.5}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.4}",
            "fontSize": "{fontSize.5}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "700": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-4}",
            "lineHeight": "{lineHeights.4}",
            "fontSize": "{fontSize.5}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-3xl": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.5}",
            "fontSize": "{fontSize.6}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.5}",
            "fontSize": "{fontSize.6}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.5}",
            "fontSize": "{fontSize.6}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.5}",
            "fontSize": "{fontSize.6}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-4xl": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.6}",
            "fontSize": "{fontSize.7}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.6}",
            "fontSize": "{fontSize.7}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.6}",
            "fontSize": "{fontSize.7}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.6}",
            "fontSize": "{fontSize.7}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-5xl": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.7}",
            "fontSize": "{fontSize.8}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.7}",
            "fontSize": "{fontSize.8}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.7}",
            "fontSize": "{fontSize.8}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.7}",
            "fontSize": "{fontSize.8}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-6xl": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.8}",
            "fontSize": "{fontSize.9}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.8}",
            "fontSize": "{fontSize.9}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.8}",
            "fontSize": "{fontSize.9}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.8}",
            "fontSize": "{fontSize.9}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-7xl": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.9}",
            "fontSize": "{fontSize.10}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.9}",
            "fontSize": "{fontSize.10}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.9}",
            "fontSize": "{fontSize.10}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.9}",
            "fontSize": "{fontSize.10}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-8xl": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.10}",
            "fontSize": "{fontSize.11}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.10}",
            "fontSize": "{fontSize.11}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.10}",
            "fontSize": "{fontSize.11}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.10}",
            "fontSize": "{fontSize.11}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
      "text-9xl": {
        "200": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-0}",
            "lineHeight": "{lineHeights.11}",
            "fontSize": "{fontSize.12}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "400": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-1}",
            "lineHeight": "{lineHeights.11}",
            "fontSize": "{fontSize.12}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "500": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-2}",
            "lineHeight": "{lineHeights.11}",
            "fontSize": "{fontSize.12}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
        "600": {
          "value": {
            "fontFamily": "{fontFamilies.inter}",
            "fontWeight": "{fontWeights.inter-3}",
            "lineHeight": "{lineHeights.11}",
            "fontSize": "{fontSize.12}",
            "letterSpacing": "{letterSpacing.0}",
            "paragraphSpacing": "{paragraphSpacing.0}",
            "paragraphIndent": "{paragraphIndent.0}",
            "textCase": "{textCase.none}",
            "textDecoration": "{textDecoration.none}",
          },
          "type": "typography",
        },
      },
    },
    "textCase": {
      "none": {
        "value": "none",
        "type": "textCase",
      },
    },
    "textDecoration": {
      "none": {
        "value": "none",
        "type": "textDecoration",
      },
    },
    "paragraphIndent": {
      "0": {
        "value": "0px",
        "type": "dimension",
      },
    },
  },
}
